// <auto-generated />
using System;
using CarDamageClaims.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarDamageClaims.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428181904_AddNotificationOutboxSubject")]
    partial class AddNotificationOutboxSubject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("CarDamageClaims.Api.Models.DamageEstimateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("DamageDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DamageRequestId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DamageRequestId");

                    b.ToTable("damage_estimate_items", (string)null);
                });

            modelBuilder.Entity("CarDamageClaims.Api.Models.DamageRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminDecisionComment")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AiEstimatedTotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AiIsCar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CarBrand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CarYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email");

                    b.HasIndex("Status");

                    b.ToTable("damage_requests", (string)null);
                });

            modelBuilder.Entity("CarDamageClaims.Api.Models.DamageRequestPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DamageRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DamageRequestId");

                    b.ToTable("damage_request_photos", (string)null);
                });

            modelBuilder.Entity("CarDamageClaims.Api.Models.NotificationOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DamageRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DamageRequestId");

                    b.HasIndex("RecipientEmail");

                    b.HasIndex("Status");

                    b.ToTable("notification_outbox", (string)null);
                });

            modelBuilder.Entity("CarDamageClaims.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CarDamageClaims.Api.Models.DamageEstimateItem", b =>
                {
                    b.HasOne("CarDamageClaims.Api.Models.DamageRequest", "DamageRequest")
                        .WithMany("EstimateItems")
                        .HasForeignKey("DamageRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamageRequest");
                });

            modelBuilder.Entity("CarDamageClaims.Api.Models.DamageRequest", b =>
                {
                    b.HasOne("CarDamageClaims.Api.Models.User", "ApprovedByUser")
                        .WithMany("ApprovedRequests")
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedByUser");
                });

            modelBuilder.Entity("CarDamageClaims.Api.Models.DamageRequestPhoto", b =>
                {
                    b.HasOne("CarDamageClaims.Api.Models.DamageRequest", "DamageRequest")
                        .WithMany("Photos")
                        .HasForeignKey("DamageRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamageRequest");
                });

            modelBuilder.Entity("CarDamageClaims.Api.Models.NotificationOutbox", b =>
                {
                    b.HasOne("CarDamageClaims.Api.Models.DamageRequest", "DamageRequest")
                        .WithMany("Notifications")
                        .HasForeignKey("DamageRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamageRequest");
                });

            modelBuilder.Entity("CarDamageClaims.Api.Models.DamageRequest", b =>
                {
                    b.Navigation("EstimateItems");

                    b.Navigation("Notifications");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("CarDamageClaims.Api.Models.User", b =>
                {
                    b.Navigation("ApprovedRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
